=== hmcts/pip-data-management/src/main/resources/schemas/non-strategic/business_and_property_division_rolls_building_daily_cause_list.json
{
  "$defs": {
    "hearingList": {
      "type": "array",
      "items": {
        "title": "Hearing list",
        "type": "object",
        "required": [
          "judge",
          "time",
          "venue",
          "type",
          "caseNumber",
          "caseName",
          "additionalInformation"
        ],
        "properties": {
          "judge": {
            "title": "Judge name",
            "type": "string",
            "default": "",
            "examples": [
              "Judge name"
            ]
          },
          "time": {
            "title": "Time of hearing",
            "type": "string",
            "default": "",
            "examples": [
              "10:30am"
            ],
            "pattern": "^\\s*\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "title": "Venue name",
            "type": "string",
            "default": "",
            "examples": [
              "This is venue name"
            ]
          },
          "type": {
            "title": "Type of hearing",
            "type": "string",
            "default": "",
            "examples": [
              "This is hearing type"
            ]
          },
          "caseNumber": {
            "title": "Case reference number",
            "type": "string",
            "default": "",
            "examples": [
              "1234"
            ]
          },
          "caseName": {
            "title": "Case name",
            "type": "string",
            "default": "",
            "examples": [
              "This is case name"
            ]
          },
          "additionalInformation": {
            "title": "Additional information",
            "type": "string",
            "default": "",
            "examples": [
              "This is additional information"
            ]
          }
        }
      }
    }
  },
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Root",
  "type": "object",
  "required": [
    "appealList",
    "businessList",
    "commercialCourt",
    "financialList",
    "insolvency&CompaniesCourt",
    "ip&EnterpriseCourt",
    "intellectualPropertyList",
    "londonCircuitCommercialCourt",
    "patentsCourt",
    "property,Trusts&ProbateList",
    "technology&ConstructionCourt",
    "admiraltyCourt",
    "companiesWindingUp",
    "competitionList",
    "pensionsList",
    "revenueList"
  ],
  "properties": {
    "appealList": {
      "$ref": "#/$defs/hearingList"
    },
    "businessList": {
      "$ref": "#/$defs/hearingList"
    },
    "commercialCourt": {
      "$ref": "#/$defs/hearingList"
    },
    "financialList": {
      "$ref": "#/$defs/hearingList"
    },
    "insolvency&CompaniesCourt": {
      "$ref": "#/$defs/hearingList"
    },
    "ip&EnterpriseCourt": {
      "$ref": "#/$defs/hearingList"
    },
    "intellectualPropertyList": {
      "$ref": "#/$defs/hearingList"
    },
    "londonCircuitCommercialCourt": {
      "$ref": "#/$defs/hearingList"
    },
    "patentsCourt": {
      "$ref": "#/$defs/hearingList"
    },
    "property,Trusts&ProbateList": {
      "$ref": "#/$defs/hearingList"
    },
    "technology&ConstructionCourt": {
      "$ref": "#/$defs/hearingList"
    },
    "admiraltyCourt": {
      "$ref": "#/$defs/hearingList"
    },
    "companiesWindingUp": {
      "$ref": "#/$defs/hearingList"
    },
    "competitionList": {
      "$ref": "#/$defs/hearingList"
    },
    "pensionsList": {
      "$ref": "#/$defs/hearingList"
    },
    "revenueList": {
      "$ref": "#/$defs/hearingList"
    }
  }
}

=== hmcts/pip-data-management/src/integrationTest/resources/data/non-strategic/business-and-property-divisions-rolls-building-daily-cause-list/businessAndPropertyDivisionRollsBuildingDailyCauseList.json
{
  "appealList": [
    {
      "judge": "Judge name",
      "time": "10.30am",
      "venue": "This is venue name",
      "type": "This is hearing type",
      "caseNumber": "1234",
      "caseName": "This is case name",
      "additionalInformation": "This is additional information"
    },
    {
      "judge": "Judge name 2",
      "time": "11:30am",
      "venue": "This is venue name 2",
      "type": "This is hearing type 2",
      "caseNumber": "5678",
      "caseName": "This is case name 2",
      "additionalInformation": "This is additional information 2"
    },
    {
      "judge": "Judge name 3",
      "time": "12:30Pm",
      "venue": "This is venue name 3",
      "type": "This is hearing type 3",
      "caseNumber": "9012",
      "caseName": "This is case name 3",
      "additionalInformation": "This is additional information 3"
    }
  ],
  "businessList": [
    {
      "judge": "Judge name",
      "time": "10:30am",
      "venue": "This is venue name",
      "type": "This is hearing type",
      "caseNumber": "1234",
      "caseName": "This is case name",
      "additionalInformation": "This is additional information"
    },
    {
      "judge": "Judge name 2",
      "time": "11:30am",
      "venue": "This is venue name 2",
      "type": "This is hearing type 2",
      "caseNumber": "5678",
      "caseName": "This is case name 2",
      "additionalInformation": "This is additional information 2"
    }
  ],
  "commercialCourt": [
    {
      "judge": "Judge name",
      "time": "10:30am",
      "venue": "This is venue name",
      "type": "This is hearing type",
      "caseNumber": "1234",
      "caseName": "This is case name",
      "additionalInformation": "This is additional information"
    }
  ],
  "financialList": [
    {
      "judge": "Judge name",
      "time": "10:30am",
      "venue": "This is venue name",
      "type": "This is hearing type",
      "caseNumber": "1234",
      "caseName": "This is case name",
      "additionalInformation": "This is additional information"
    }
  ],
  "insolvency&CompaniesCourt": [
    {
      "judge": "Judge name",
      "time": "10:30am",
      "venue": "This is venue name",
      "type": "This is hearing type",
      "caseNumber": "1234",
      "caseName": "This is case name",
      "additionalInformation": "This is additional information"
    }
  ],
  "ip&EnterpriseCourt": [],
  "intellectualPropertyList": [
    {
      "judge": "Judge name",
      "time": "10:30am",
      "venue": "This is venue name",
      "type": "This is hearing type",
      "caseNumber": "1234",
      "caseName": "This is case name",
      "additionalInformation": "This is additional information"
    },
    {
      "judge": "Judge name 2",
      "time": "11:30am",
      "venue": "This is venue name 2",
      "type": "This is hearing type 2",
      "caseNumber": "5678",
      "caseName": "This is case name 2",
      "additionalInformation": "This is additional information 2"
    }
  ],
  "londonCircuitCommercialCourt": [
    {
      "judge": "Judge name",
      "time": "10:30am",
      "venue": "This is venue name",
      "type": "This is hearing type",
      "caseNumber": "1234",
      "caseName": "This is case name",
      "additionalInformation": "This is additional information"
    }
  ],
  "patentsCourt": [
    {
      "judge": "Judge name",
      "time": "10:30am",
      "venue": "This is venue name",
      "type": "This is hearing type",
      "caseNumber": "1234",
      "caseName": "This is case name",
      "additionalInformation": "This is additional information"
    }
  ],
  "property,Trusts&ProbateList": [
    {
      "judge": "Judge name",
      "time": "10:30am",
      "venue": "This is venue name",
      "type": "This is hearing type",
      "caseNumber": "1234",
      "caseName": "This is case name",
      "additionalInformation": "This is additional information"
    },
    {
      "judge": "Judge name 2",
      "time": "11:30am",
      "venue": "This is venue name 2",
      "type": "This is hearing type 2",
      "caseNumber": "5678",
      "caseName": "This is case name 2",
      "additionalInformation": "This is additional information 2"
    }
  ],
  "technology&ConstructionCourt": [
    {
      "judge": "Judge name",
      "time": "10:30am",
      "venue": "This is venue name",
      "type": "This is hearing type",
      "caseNumber": "1234",
      "caseName": "This is case name",
      "additionalInformation": "This is additional information"
    }
  ],
  "admiraltyCourt": [
    {
      "judge": "Judge name",
      "time": "10:30am",
      "venue": "This is venue name",
      "type": "This is hearing type",
      "caseNumber": "1234",
      "caseName": "This is case name",
      "additionalInformation": "This is additional information"
    }
  ],
  "companiesWindingUp": [
    {
      "judge": "Judge name",
      "time": "10:30am",
      "venue": "This is venue name",
      "type": "This is hearing type",
      "caseNumber": "1234",
      "caseName": "This is case name",
      "additionalInformation": "This is additional information"
    },
    {
      "judge": "Judge name 2",
      "time": "11:30am",
      "venue": "This is venue name 2",
      "type": "This is hearing type 2",
      "caseNumber": "5678",
      "caseName": "This is case name 2",
      "additionalInformation": "This is additional information 2"
    }
  ],
  "competitionList": [
    {
      "judge": "Judge name",
      "time": "10:30am",
      "venue": "This is venue name",
      "type": "This is hearing type",
      "caseNumber": "1234",
      "caseName": "This is case name",
      "additionalInformation": "This is additional information"
    }
  ],
  "pensionsList": [
    {
      "judge": "Judge name",
      "time": "10:30am",
      "venue": "This is venue name",
      "type": "This is hearing type",
      "caseNumber": "1234",
      "caseName": "This is case name",
      "additionalInformation": "This is additional information"
    }
  ],
  "revenueList": []
}
